export enum SUPPORTED_TOPICS {
    UKRAINE = 'UKRAINE',
    GAZA = 'GAZA',
    PALESTINE = 'PALESTINE',
    US_ELECTION = 'US_ELECTION',
    ECONOMY = 'ECONOMY',
    BITCOIN = 'BITCOIN',
    TECHNOLOGY = 'TECHNOLOGY',
    STARTUPS = 'STARTUPS'
}